
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { Sitecore } from "./_.Sitecore.Override"
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { ComponentRendering, RouteData, Field, ImageField, FileField, LinkField } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { DefaultComponentProps } from '@/lib/component-props';


export namespace ChakravyuhRenderingParameters.Fields {
    export type RevertView = { 
        fields?: { 
            /**
            * Represents the revertColumns field (bfa8075e-1946-44ca-824a-a39ca6f7793c).
            */
            revertColumns: Field<boolean>;
 
        }
 }; 
}

export namespace ChakravyuhFoundation.Fields {
    export type StyleClass = { 
        fields?: { 
            /**
            * Represents the Size field (458cb3b1-e720-4b82-9c3a-ffbc2f824635).
            */
            Size: Field<string>;
 
        }
 }; 
}

export namespace ChakravyuhFoundation.Fields {
    export type Enum = { 
        fields?: { 
            /**
            * Represents the Name field (eeb6cdb4-cec6-497e-af83-b0721a971f58).
            */
            Name: Field<string>;

            /**
            * Represents the Value field (afadffcd-1279-46fa-8b99-0208083636ff).
            */
            Value: Field<string>;
 
        }
 }; 
}

export namespace ChakravyuhFoundation.Fields {
    export type Image = { 
        fields?: { 
            /**
            * Represents the PageImage field (04a082db-8e0d-44c0-ad26-0fbab90a124c).
            */
            PageImage: ImageField;
 
        }
 }; 
}

export namespace ChakravyuhFoundation.Fields {
    export type Name = { 
        fields?: { 
            /**
            * Represents the First Name field (89417d37-58a6-4ea9-a4e5-ea085910f828).
            */
            Firstname: Field<string>;

            /**
            * Represents the Last Name field (bc479562-581b-451c-af74-2986dfd073af).
            */
            Lastname: Field<string>;
 
        }
 }; 
}

export namespace ChakravyuhFoundation.Fields {
    export type Title = { 
        fields?: { 
            /**
            * Represents the PageTitle field (8ea528e0-c672-4b58-8cf6-fd5ac3e160e3).
            */
            PageTitle: Field<string>;

            /**
            * Represents the PageTitleSize field (5def12cf-6eda-46a6-bc0a-bcb48b6b69e5).
            */
            PageTitleSize?: Sitecore.Override.ItemEx;
 
        }
 }; 
}

export namespace ChakravyuhFoundation.Fields {
    export type NewsDetail = { 
        fields?: { 
            /**
            * Represents the newsImage field (e2324d84-8c7c-46a3-8f50-a5cb27f6b665).
            */
            newsImage: ImageField;

            /**
            * Represents the newsReporter field (1f39ae02-22c1-4381-abcd-1a2dcc121342).
            */
            newsReporter: Field<string>;

            /**
            * Represents the Body - use tailwind css for body field (af4ac833-e0ff-4102-950d-e32a4ad0b70e).
            */
            newsSubject: Field<string>;

            /**
            * Represents the newsTitle field (e00ae5a1-a5ec-4ba0-b8f7-adfbfc823781).
            */
            newsTitle: Field<string>;

            /**
            * Represents the PublishingDate field (326518a6-ece3-41a9-80aa-e3f15eb6473c).
            */
            PublishingDate: Field<string>;
 
        }
 }; 
}

export namespace ChakravyuhFoundation.Fields {
    export type NewsList = { 
        fields?: { 
            /**
            * Represents the addNewsItems field (f9d86793-062c-4951-9b10-663c83d05fc6).
            */
            addNewsItems: Field<string>;
 
        }
 }; 
}


