
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { Sitecore } from "./_.Sitecore.Override"
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { ComponentRendering, RouteData, Field, ImageField, FileField, LinkField } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { DefaultComponentProps } from '@/lib/component-props';


export namespace $(layer).$(module).Sitecore.templates.Chakravyuh.Fields {
    export type Banner = { 
        fields?: { 
            /**
            * Represents the Description field (d17a1ae8-fac7-4532-b4ff-a342654ee913).
            */
            Description: Field<string>;

            /**
            * Represents the Title field (b99b5aa6-e344-4e4d-a6cf-014c535875ec).
            */
            Title: Field<string>;
 
        }
 }; 
}


